---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.17.5
    app.quarkus.io/build-timestamp: 2024-12-24 - 14:28:17 +0000
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.17.5
    app.quarkus.io/build-timestamp: 2024-12-24 - 14:28:17 +0000
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.17.5
        app.quarkus.io/build-timestamp: 2024-12-24 - 14:28:17 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: test
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/estoi/test:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: test
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
